#!/bin/bash
# NUM_LINES="$(cat qme_questions | wc -l)"
# cat ./qme_questions.txt | head -n $(shuf -i 1-84 -n 1) | tail -n 1
# date >> ./qme_session.log 
# date >> ./qme_alltime.log

#clear qme_session.log for each session by
#adding the foll to the end of ~/.bashrc
#rm ~/bin/qme_session.log

QME_QUESTIONS='/home/zeus/Documents/Terminal_Quiz/qme_questions.txt'

case "$1" in
    -q|--question)
        sed "$2q;d" $QME_QUESTIONS
    ;;
    *)
        cat $QME_QUESTIONS | head -n $(shuf -i 1-84 -n 1) | tail -n 1
esac

date >> ./qme_session.log 
date >> ./qme_alltime.log
