.\" manpage for qme.
.\" Contact Bharath to correct errors or typos.
.TH QME 1 "Jan 2020" "1.0" "User Commands"
.SH NAME
.PP
qme \- flashcard management program
.SH SYNOPSIS
.PP
qme [\f[I]option\f[R]]
.SH DESCRIPTION
.PP
Displays a random question from a question-bank. Provides tools to edit and maintain the question and answer database. Preloaded with basic Linux terminal exercises.



.fi
.SH OPTIONS
.TP
.B \-c  
Display number of times a random question was shown during this terminal session.

.TP
.B \-t 
Display total number of times a random question was shown.

.TP
.B \-q, \-\-question \f[I]NUM\f[R]
Display \f[I]NUM\f[R]th question in the question-bank.

.TP
.B \-a, \-\-answer \f[I]NUM\f[R]
Display \f[I]NUM\f[R]th answer in the answer-bank

.TP
.B \-\-add <\f[I]question\f[R]>  <\f[I]answer\f[R]>
Add a question and answer to the database.

.TP
.B \-\-remove \f[I]NUM\f[R]
Remove \f[I]NUM\f[R]th question and answer in the database
.TP

.B \-\-clear\-log
Clear alltime log. This sets total count of random questions seen to zero.
.TP

.B \-\-reset
Reset the question and answer database to default.
.TP

\f[R]
.fi
.SH EXAMPLES
.PP
To add the question "How many vowels in the alphabet" and corresponding answer "5":

.IP
.nf
\f[C]
qme --add "How many vowels in the alphabet" "5"
\f[R]
.fi

\f[R]
.fi
.SH AUTHORS
.PP
Bharath & Gautham

https://github.com/bharath-kamath705 \p
https://github.com/doctor-entropy
